server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 802866
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: debug

